# Generated by Django 3.0.5 on 2021-12-26 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('sub', models.CharField(max_length=500)),
                ('msg', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther', models.CharField(max_length=500)),
                ('phoneno', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('header', models.CharField(max_length=500)),
                ('text', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=500)),
                ('areaadmin', models.CharField(max_length=500)),
                ('area', models.CharField(max_length=500)),
                ('wardno', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('taluka', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('pincode', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernames', models.CharField(max_length=500)),
                ('phoneno', models.CharField(max_length=500)),
                ('area', models.CharField(max_length=500)),
                ('wardno', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('taluka', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('pincode', models.CharField(max_length=500)),
                ('utype', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
